// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using arroyoSeco.Infrastructure.Data;

#nullable disable

namespace arroyoSeco.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118111048_AddComprobanteToReserva")]
    partial class AddComprobanteToReserva
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.Alojamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Banos")
                        .HasColumnType("int");

                    b.Property<string>("FotoPrincipal")
                        .HasColumnType("longtext");

                    b.Property<int>("Habitaciones")
                        .HasColumnType("int");

                    b.Property<int>("MaxHuespedes")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OferenteId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OferenteId");

                    b.ToTable("Alojamientos");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.FotoAlojamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlojamientoId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AlojamientoId");

                    b.ToTable("FotosAlojamiento");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlojamientoId")
                        .HasColumnType("int");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ComprobanteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("AlojamientoId");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Notificaciones.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Leida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlAccion")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Solicitudes.SolicitudOferente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminId")
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mensaje")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Estatus");

                    b.ToTable("SolicitudesOferente");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Usuarios.Oferente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroAlojamientos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Oferentes");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.Alojamiento", b =>
                {
                    b.HasOne("arroyoSeco.Domain.Entities.Usuarios.Oferente", "Oferente")
                        .WithMany("Alojamientos")
                        .HasForeignKey("OferenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Oferente");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.FotoAlojamiento", b =>
                {
                    b.HasOne("arroyoSeco.Domain.Entities.Alojamientos.Alojamiento", "Alojamiento")
                        .WithMany("Fotos")
                        .HasForeignKey("AlojamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alojamiento");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.Reserva", b =>
                {
                    b.HasOne("arroyoSeco.Domain.Entities.Alojamientos.Alojamiento", "Alojamiento")
                        .WithMany("Reservas")
                        .HasForeignKey("AlojamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alojamiento");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.Alojamiento", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Usuarios.Oferente", b =>
                {
                    b.Navigation("Alojamientos");
                });
#pragma warning restore 612, 618
        }
    }
}
